---

- name: Deploy to EKS
  hosts: localhost
  tasks:
  - name: Deploy Django App to Pods
    shell: kubectl apply -f app.yml 
  - name: Horizontal autoscale
    shell: kubectl autoscale deployment cloud-app --cpu-percent=50 --min=1 --max=10

